service: espn-fantasy-my-matchup
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  region: us-east-1
  memorySize: 512
  timeout: 60

  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "secretsmanager:*"
      Resource: arn:aws:secretsmanager:us-east-1:978072805127:secret:espn-fantasy-league-creds-IKFhtX

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/espn-fantasy-league-creds~true}
  pythonRequirements:
    dockerizePip: true
    dockerSsh: true
    dockerSshSymlink: ~/.ssh

functions:
  handler:
    handler: espn_fantasy_my_matchup/handler.handle
    environment:
      LEAGUE_SWID: ${self:custom.secrets.LEAGUE_SWID}
      LEAGUE_ESPN_S2: ${self:custom.secrets.LEAGUE_ESPN_S2}
      LEAGUE_ID: ${self:custom.secrets.LEAGUE_ID}
      LEAGUE_YEAR: 2021

plugins:
  - serverless-python-requirements